// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxkxkddttnhzaxmnqcfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4a3hrZGR0dG5oemF4bW5xY2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjQyMDksImV4cCI6MjA2NTMwMDIwOX0.hKidHVYdf88782r2aNo7ECIcw4Wl3wWVcZ2kXBhcX9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);